function fh = scatterPlotRMSE(con1,con2)
figNameRmse = sprintf([con2.descript '_vs_' con1.descript '_rmse_common_voxels_map']);
fh = mrvNewGraphWin(figNameRmse);
% [ymap,x]  = hist3([con1.rmse;con2.rmse]',{[10:1:70], [10:1:70]});
[ymap,x]  = hist3([con1.rmse;con2.rmse]');
ymap = ymap./length(con2.rmse);
sh   = imagesc(flipud(log10(ymap)));
cm   = colormap(flipud(hot)); view(0,90);
axis('square')      
set(gca, ...
    'xlim',[1 length(x{1})],...
    'ylim',[1 length(x{1})], ...
    'ytick',[1 (length(x{1})/2) length(x{1})], ...
    'xtick',[1 (length(x{1})/2) length(x{1})], ...
    'yticklabel',[x{1}(end) x{1}(round(end/2)) x{1}(1)], ...
    'xticklabel',[x{1}(1)   x{1}(round(end/2)) x{1}(end)], ...
    'tickdir','out','ticklen',[.025 .05],'box','off', ...
    'fontsize',16,'visible','on')
hold on
plot3([1 length(x{1})],[length(x{1}) 1],[max(ymap(:)) max(ymap(:))],'k-','linewidth',1)
ylabel([con1.descript ' rmse'], 'fontsize', 16)
xlabel([con2.descript ' rmse'], 'fontsize', 16)
cb = colorbar;
tck = get(cb,'ytick');
set(cb,'yTick',[min(tck)  mean(tck) max(tck)], ...
    'yTickLabel',round(1000*10.^[min(tck),...
    mean(tck), ...
    max(tck)])/1000, ...
    'tickdir','out','ticklen',[.025 .05],'box','on', ...
    'fontsize',16,'visible','on')
end